import type { NavItem } from './types';
import {
  LayoutDashboard, Ticket, PlusCircle, Inbox, Users, BarChart3, CheckSquare, ClipboardCheck, BookOpen, FileEdit, MessageSquare, Activity, Bell, Settings, Building2, ShieldCheck, CreditCard, Calendar, Clock, FileText, FolderKanban, Users2, Sparkles, Archive, User, LayoutTemplate, ClipboardList, Calculator, Database, FileUp, Layers, FileSpreadsheet, Star, Search,
} from './icons';

export const etmsNavItems: NavItem[] = [
// ── Dashboard ──────────────────────────────────────────────────────────
  {
    id: 'dashboard',
    title: 'Dashboard',
    href: '/app/dashboard',
    icon: LayoutDashboard,
    keywords: ['home', 'command', 'overview'],
    searchPriority: 10,
    legacyGroup: 'Executive Overview',
  },
  {
    id: 'operator-dashboard',
    title: 'Operator Dashboard',
    href: '/app/operator-dashboard',
    icon: Inbox,
    roles: ['ADMIN', 'HR', 'MANAGER', 'EMPLOYEE'],
    keywords: ['operator', 'queue', 'my work'],
    searchPriority: 11,
  },

  // ── Tickets ──────────────────────────────────────────────────────────────
  {
    id: 'tickets-mine',
    title: 'My Tickets',
    href: '/app/tickets?scope=mine',
    icon: Ticket,
    roles: ['ADMIN', 'HR', 'MANAGER', 'EMPLOYEE'],
    featureFlag: 'VITE_ENABLE_TICKETING',
    keywords: ['ticket', 'my', 'requests'],
    searchPriority: 2,
    legacyGroup: 'Service Management',
  },
  {
    id: 'tickets-team',
    title: 'Team Tickets',
    href: '/app/tickets?scope=team',
    icon: Users,
    roles: ['ADMIN', 'HR', 'MANAGER'],
    featureFlag: 'VITE_ENABLE_TICKETING',
    keywords: ['ticket', 'team'],
    searchPriority: 15,
    legacyGroup: 'Service Management',
  },
  {
    id: 'tickets-all',
    title: 'All Tickets',
    href: '/app/tickets?scope=all',
    icon: Layers,
    roles: ['ADMIN', 'HR', 'MANAGER'],
    featureFlag: 'VITE_ENABLE_TICKETING',
    keywords: ['ticket', 'all', 'list'],
    searchPriority: 16,
    legacyGroup: 'Service Management',
  },
  {
    id: 'tickets-legacy-list',
    title: 'Tickets',
    href: '/app/tickets',
    icon: Ticket,
    roles: ['ADMIN', 'HR', 'MANAGER', 'EMPLOYEE'],
    featureFlag: 'VITE_ENABLE_TICKETING',
    legacyGroup: 'Service Management',
  },
  {
    id: 'tickets-create',
    title: 'Create Ticket',
    href: '/app/tickets/new',
    icon: PlusCircle,
    roles: ['ADMIN', 'HR', 'MANAGER', 'EMPLOYEE'],
    featureFlag: 'VITE_ENABLE_TICKETING',
    keywords: ['create', 'new', 'ticket', 'submit'],
    searchPriority: 1,
    legacyGroup: 'Service Management',
  },

  // ── Assignments ──────────────────────────────────────────────────────────
  {
    id: 'assignments-mine',
    title: 'Assigned To Me',
    href: '/app/my-queue',
    icon: Inbox,
    roles: ['ADMIN', 'HR', 'MANAGER', 'EMPLOYEE'],
    featureFlag: 'VITE_ENABLE_TICKET_ASSIGNMENTS',
    keywords: ['queue', 'assigned', 'my'],
    searchPriority: 3,
    legacyGroup: 'Work Queues',
  },
  {
    id: 'assignments-team',
    title: 'Team Assignments',
    href: '/app/team-queue',
    icon: Users,
    roles: ['ADMIN', 'HR', 'MANAGER'],
    featureFlag: 'VITE_ENABLE_TICKET_ASSIGNMENTS',
    keywords: ['team', 'queue', 'assignments'],
    searchPriority: 20,
    legacyGroup: 'Work Queues',
  },
  {
    id: 'assignments-workload',
    title: 'Workload',
    href: '/app/assignment-analytics',
    icon: BarChart3,
    roles: ['ADMIN', 'HR', 'MANAGER'],
    featureFlag: 'VITE_ENABLE_TICKET_ASSIGNMENTS',
    keywords: ['workload', 'analytics', 'assignment'],
    searchPriority: 25,
    legacyGroup: 'Work Queues',
  },

  // ── Approvals ────────────────────────────────────────────────────────────
  {
    id: 'approvals-pending',
    title: 'Pending',
    href: '/app/my-approvals?status=pending',
    icon: ClipboardCheck,
    featureFlag: 'VITE_ENABLE_APPROVAL_ENGINE',
    keywords: ['approval', 'pending'],
    searchPriority: 18,
    legacyGroup: 'Approvals',
  },
  {
    id: 'approvals-approved',
    title: 'Approved',
    href: '/app/my-approvals?status=approved',
    icon: CheckSquare,
    featureFlag: 'VITE_ENABLE_APPROVAL_ENGINE',
    keywords: ['approval', 'approved'],
    searchPriority: 30,
    legacyGroup: 'Approvals',
  },
  {
    id: 'approvals-rejected',
    title: 'Rejected',
    href: '/app/my-approvals?status=rejected',
    icon: ClipboardList,
    featureFlag: 'VITE_ENABLE_APPROVAL_ENGINE',
    keywords: ['approval', 'rejected'],
    searchPriority: 31,
    legacyGroup: 'Approvals',
  },
  {
    id: 'approvals-dashboard',
    title: 'Approval Dashboard',
    href: '/app/approvals',
    icon: CheckSquare,
    featureFlag: 'VITE_ENABLE_APPROVAL_ENGINE',
    keywords: ['approval', 'dashboard'],
    searchPriority: 22,
    legacyGroup: 'Approvals',
  },
  {
    id: 'approvals-analytics',
    title: 'Approval Analytics',
    href: '/app/approval-analytics',
    icon: BarChart3,
    featureFlag: 'VITE_ENABLE_APPROVAL_ENGINE',
    legacyGroup: 'Approvals',
  },

  // ── Knowledge Base ───────────────────────────────────────────────────────
  {
    id: 'kb-articles',
    title: 'Articles',
    href: '/app/knowledge-base',
    icon: BookOpen,
    featureFlag: 'VITE_ENABLE_KNOWLEDGE_BASE',
    keywords: ['knowledge', 'kb', 'articles', 'help'],
    searchPriority: 5,
    legacyGroup: 'Knowledge Base',
  },
  {
    id: 'kb-categories',
    title: 'Categories',
    href: '/app/knowledge-base?tab=categories',
    icon: Layers,
    featureFlag: 'VITE_ENABLE_KNOWLEDGE_BASE',
    keywords: ['categories', 'knowledge', 'kb'],
    searchPriority: 6,
    legacyGroup: 'Knowledge Base',
  },
  {
    id: 'kb-search',
    title: 'Search',
    href: '/app/knowledge-base?search=true',
    icon: Search,
    featureFlag: 'VITE_ENABLE_KNOWLEDGE_BASE',
    keywords: ['search', 'kb', 'articles', 'lookup'],
    searchPriority: 7,
    legacyGroup: 'Knowledge Base',
  },
  {
    id: 'kb-legacy-home',
    title: 'Knowledge Base',
    href: '/app/knowledge-base',
    icon: BookOpen,
    featureFlag: 'VITE_ENABLE_KNOWLEDGE_BASE',
    legacyGroup: 'Knowledge Base',
  },
  {
    id: 'kb-editor',
    title: 'Article Editor',
    href: '/app/article-editor',
    icon: FileEdit,
    roles: ['MANAGER', 'ADMIN', 'SUPER_ADMIN', 'EMPLOYEE'],
    featureFlag: 'VITE_ENABLE_KNOWLEDGE_BASE',
    legacyGroup: 'Knowledge Base',
  },
  {
    id: 'kb-analytics',
    title: 'KB Analytics',
    href: '/app/kb-analytics',
    icon: BarChart3,
    roles: ['MANAGER', 'ADMIN', 'SUPER_ADMIN', 'HR'],
    featureFlag: 'VITE_ENABLE_KNOWLEDGE_BASE',
    legacyGroup: 'Knowledge Base',
  },

  // ── Communications ───────────────────────────────────────────────────────
  {
    id: 'comms-chat',
    title: 'Chat',
    href: '/app/communications',
    icon: MessageSquare,
    featureFlag: 'VITE_ENABLE_COMMUNICATION_TRACKING',
    keywords: ['chat', 'communications', 'messages'],
    searchPriority: 20,
    legacyGroup: 'Communications',
  },
  {
    id: 'comms-announcements',
    title: 'Announcements',
    href: '/app/meetups',
    icon: Users2,
    featureFlag: 'VITE_ENABLE_COMMUNICATION_TRACKING',
    keywords: ['announcements', 'meetups', 'broadcasts'],
    searchPriority: 21,
    legacyGroup: 'Communications',
  },
  {
    id: 'comms-discussions',
    title: 'Discussions',
    href: '/app/updates/daily',
    icon: Sparkles,
    featureFlag: 'VITE_ENABLE_COMMUNICATION_TRACKING',
    keywords: ['discussions', 'forum', 'updates', 'chat'],
    searchPriority: 22,
    legacyGroup: 'Communications',
  },
  {
    id: 'comms-legacy',
    title: 'Communications',
    href: '/app/communications',
    icon: MessageSquare,
    featureFlag: 'VITE_ENABLE_COMMUNICATION_TRACKING',
    legacyGroup: 'Communications',
  },
  {
    id: 'comms-timeline',
    title: 'Activity Timeline',
    href: '/app/activity-timeline',
    icon: Activity,
    featureFlag: 'VITE_ENABLE_COMMUNICATION_TRACKING',
    legacyGroup: 'Communications',
  },
  {
    id: 'comms-analytics',
    title: 'Communication Analytics',
    href: '/app/communication-analytics',
    icon: BarChart3,
    featureFlag: 'VITE_ENABLE_COMMUNICATION_TRACKING',
    legacyGroup: 'Communications',
  },
];
