import type { NavItem } from './types';
import {
  LayoutDashboard, Ticket, PlusCircle, Inbox, Users, BarChart3, CheckSquare, ClipboardCheck, BookOpen, FileEdit, MessageSquare, Activity, Bell, Settings, Building2, ShieldCheck, CreditCard, Calendar, Clock, FileText, FolderKanban, Users2, Sparkles, Archive, User, LayoutTemplate, ClipboardList, Calculator, Database, FileUp, Layers, FileSpreadsheet, Star,
} from './icons';

export const legacyNavItems: NavItem[] = [
// ── Legacy workforce modules (top-level links in ETMS mode) ───────────────
  {
    id: 'legacy-payroll',
    title: 'Payroll',
    href: '/app/payroll',
    icon: CreditCard,
    roles: ['ADMIN', 'HR'],
    legacyOnly: true,
    keywords: ['payroll', 'salary', 'legacy'],
    searchPriority: 80,
    legacyGroup: 'Workforce Intelligence',
  },
  {
    id: 'legacy-attendance',
    title: 'Attendance',
    href: '/app/attendance',
    icon: Clock,
    legacyOnly: true,
    keywords: ['attendance', 'presence', 'legacy'],
    searchPriority: 81,
    legacyGroup: 'Human Capital Management',
  },
  {
    id: 'legacy-leaves',
    title: 'Leaves',
    href: '/app/leaves',
    icon: Calendar,
    legacyOnly: true,
    keywords: ['leaves', 'time off', 'legacy'],
    searchPriority: 82,
    legacyGroup: 'Human Capital Management',
  },
  {
    id: 'legacy-projects',
    title: 'Projects',
    href: '/app/projects',
    icon: FolderKanban,
    legacyOnly: true,
    keywords: ['projects', 'legacy'],
    searchPriority: 83,
  },
  {
    id: 'legacy-meetups',
    title: 'Meetups',
    href: '/app/meetups',
    icon: Users2,
    legacyOnly: true,
    keywords: ['meetups', 'legacy'],
    searchPriority: 84,
    legacyGroup: 'Executive Overview',
  },
  {
    id: 'legacy-updates',
    title: 'Updates',
    href: '/app/updates/daily',
    icon: Sparkles,
    legacyOnly: true,
    keywords: ['updates', 'legacy'],
    searchPriority: 85,
  },
  {
    id: 'legacy-reports',
    title: 'Reports',
    href: '/app/reports',
    icon: BarChart3,
    roles: ['ADMIN', 'HR', 'MANAGER'],
    legacyOnly: true,
    keywords: ['reports', 'legacy'],
    searchPriority: 86,
    legacyGroup: 'Strategic Assets',
  },
  {
    id: 'legacy-documents',
    title: 'Documents',
    href: '/app/documents',
    icon: FileText,
    roles: ['ADMIN', 'HR'],
    legacyOnly: true,
    keywords: ['documents', 'vault', 'legacy'],
    searchPriority: 87,
    legacyGroup: 'Strategic Assets',
  },
];
