import type { NavItem } from './types';
import {
  LayoutDashboard, Ticket, PlusCircle, Inbox, Users, BarChart3, CheckSquare, ClipboardCheck, BookOpen, FileEdit, MessageSquare, Activity, Bell, Settings, Building2, ShieldCheck, CreditCard, Calendar, Clock, FileText, FolderKanban, Users2, Sparkles, Archive, User, LayoutTemplate, ClipboardList, Calculator, Database, FileUp, Layers, FileSpreadsheet, Star,
} from './icons';

export const payrollNavItems: NavItem[] = [
// ── Legacy payroll deep-nav (legacy display mode only) ─────────────────────
  {
    id: 'legacy-payroll-governance',
    title: 'Governance Core',
    href: '/app/payroll/governance',
    icon: ShieldCheck,
    roles: ['ADMIN', 'HR'],
    legacyGroup: 'Workforce Intelligence',
  },
  {
    id: 'legacy-payroll-components',
    title: 'Pay Components',
    href: '/app/payroll/components',
    icon: LayoutTemplate,
    roles: ['ADMIN', 'HR'],
    legacyGroup: 'Workforce Intelligence',
  },
  {
    id: 'legacy-payroll-structures',
    title: 'Salary Matrix',
    href: '/app/payroll/structures',
    icon: CreditCard,
    roles: ['ADMIN', 'HR'],
    legacyGroup: 'Workforce Intelligence',
  },
  {
    id: 'legacy-payroll-cycles',
    title: 'Payroll Engine',
    href: '/app/payroll/cycles',
    icon: Calendar,
    roles: ['ADMIN', 'HR'],
    legacyGroup: 'Operational Cycles',
  },
  {
    id: 'legacy-payroll-bulk',
    title: 'Bulk Ingestion',
    href: '/app/payroll/bulk',
    icon: FileUp,
    roles: ['ADMIN', 'HR'],
    legacyGroup: 'Operational Cycles',
  },
  {
    id: 'legacy-payroll-assignments',
    title: 'Salary Assignments',
    href: '/app/payroll/assignments',
    icon: Users2,
    roles: ['ADMIN', 'HR'],
    legacyGroup: 'Operational Cycles',
  },
  {
    id: 'legacy-payroll-approvals',
    title: 'Approval Queue',
    href: '/app/payroll/governance/approvals',
    icon: ClipboardList,
    roles: ['ADMIN', 'HR', 'MANAGER'],
    legacyGroup: 'Operational Cycles',
  },
  {
    id: 'legacy-payroll-pf',
    title: 'Statutory Ledger',
    href: '/app/payroll/compliance/pf',
    icon: ShieldCheck,
    roles: ['ADMIN', 'HR'],
    legacyGroup: 'Governance & Compliance',
  },
  {
    id: 'legacy-payroll-compliance',
    title: 'Compliance Audit',
    href: '/app/payroll/compliance',
    icon: ShieldCheck,
    roles: ['ADMIN', 'HR'],
    legacyGroup: 'Governance & Compliance',
  },
  {
    id: 'legacy-payroll-tax',
    title: 'Tax Jurisdictions',
    href: '/app/payroll/tax-slabs',
    icon: Calculator,
    roles: ['ADMIN'],
    legacyGroup: 'Governance & Compliance',
  },
  {
    id: 'legacy-payroll-journals',
    title: 'Capital Journals',
    href: '/app/payroll/finance/journals',
    icon: FileText,
    roles: ['ADMIN', 'FINANCE'],
    legacyGroup: 'Financial Orchestration',
  },
  {
    id: 'legacy-payroll-disbursements',
    title: 'Unified Disbursements',
    href: '/app/payroll/finance/disbursements',
    icon: CreditCard,
    roles: ['ADMIN', 'FINANCE'],
    legacyGroup: 'Financial Orchestration',
  },
  {
    id: 'legacy-payroll-erp',
    title: 'ERP Sync Center',
    href: '/app/payroll/finance/erp-export',
    icon: Database,
    roles: ['ADMIN', 'FINANCE'],
    legacyGroup: 'Financial Orchestration',
  },
  {
    id: 'legacy-payroll-analytics',
    title: 'Workforce Trends',
    href: '/app/payroll/analytics',
    icon: BarChart3,
    roles: ['ADMIN', 'HR', 'MANAGER'],
    legacyGroup: 'Predictive Analytics',
  },
  {
    id: 'legacy-payroll-variance',
    title: 'Variance Matrix',
    href: '/app/payroll/variance',
    icon: ClipboardList,
    roles: ['ADMIN', 'HR'],
    legacyGroup: 'Predictive Analytics',
  },
  {
    id: 'legacy-profile',
    title: 'My Identity',
    href: '/app/profile',
    icon: User,
    roles: ['ADMIN', 'HR', 'EMPLOYEE'],
    legacyGroup: 'Personalized Portal',
  },
  {
    id: 'legacy-payslips',
    title: 'Digital Payslips',
    href: '/app/payroll/my-payslips',
    icon: FileText,
    roles: ['ADMIN', 'HR', 'EMPLOYEE'],
    legacyGroup: 'Personalized Portal',
  },
  {
    id: 'legacy-deductions',
    title: 'Benefits Matrix',
    href: '/app/payroll/deductions',
    icon: Calculator,
    roles: ['ADMIN', 'HR', 'EMPLOYEE'],
    legacyGroup: 'Personalized Portal',
  },
  {
    id: 'legacy-employees',
    title: 'Entity Directory',
    href: '/app/employees',
    icon: Users,
    roles: ['ADMIN', 'HR', 'MANAGER'],
    legacyGroup: 'Human Capital Management',
  },
  {
    id: 'legacy-departments-inline',
    title: 'Org Architecture',
    href: '/app/departments',
    icon: Building2,
    legacyGroup: 'Human Capital Management',
  },
  {
    id: 'legacy-attendance-inline',
    title: 'Presence Logs',
    href: '/app/attendance',
    icon: Clock,
    legacyGroup: 'Human Capital Management',
  },
  {
    id: 'legacy-leaves-inline',
    title: 'Lifecycle Leaves',
    href: '/app/leaves',
    icon: Calendar,
    legacyGroup: 'Human Capital Management',
  },
  {
    id: 'legacy-documents-inline',
    title: 'Document Vault',
    href: '/app/documents',
    icon: FileText,
    roles: ['ADMIN', 'HR'],
    legacyGroup: 'Strategic Assets',
  },
  {
    id: 'legacy-reports-inline',
    title: 'Insight Reports',
    href: '/app/reports',
    icon: BarChart3,
    roles: ['ADMIN', 'HR', 'MANAGER'],
    legacyGroup: 'Strategic Assets',
  },
  {
    id: 'legacy-settings-inline',
    title: 'Platform Settings',
    href: '/app/payroll/settings',
    icon: Settings,
    roles: ['ADMIN'],
    legacyGroup: 'Strategic Assets',
  },
  {
    id: 'legacy-meetups-inline',
    title: 'Global Meet-ups',
    href: '/app/meetups',
    icon: Users2,
    legacyGroup: 'Executive Overview',
  },
  {
    id: 'legacy-dashboard-inline',
    title: 'Command Dashboard',
    href: '/app/dashboard',
    icon: LayoutDashboard,
    legacyGroup: 'Executive Overview',
  },
  {
    id: 'legacy-payroll-control',
    title: 'Payroll Control',
    href: '/app/payroll',
    icon: LayoutDashboard,
    roles: ['ADMIN', 'HR'],
    legacyGroup: 'Workforce Intelligence',
  },
];
